// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDkRungn4FI0xwt51ch_Enp5C2iImgGbc',
    appId: '1:33711759292:web:6e1292728a5a420297d5b9',
    messagingSenderId: '33711759292',
    projectId: 'aksara-a9457',
    authDomain: 'aksara-a9457.firebaseapp.com',
    databaseURL: 'https://aksara-a9457-default-rtdb.firebaseio.com',
    storageBucket: 'aksara-a9457.firebasestorage.app',
    measurementId: 'G-FV54DFR07K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnbz8OpQc2DnQW8R4S0tMBpyfkbwrKUh4',
    appId: '1:33711759292:android:117e3d2447e12fba97d5b9',
    messagingSenderId: '33711759292',
    projectId: 'aksara-a9457',
    databaseURL: 'https://aksara-a9457-default-rtdb.firebaseio.com',
    storageBucket: 'aksara-a9457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNUDI8mPqnEpMavjqUEE8Il7imlikeMgU',
    appId: '1:33711759292:ios:f294f271f9df24c597d5b9',
    messagingSenderId: '33711759292',
    projectId: 'aksara-a9457',
    databaseURL: 'https://aksara-a9457-default-rtdb.firebaseio.com',
    storageBucket: 'aksara-a9457.firebasestorage.app',
    androidClientId: '33711759292-36bo8m4d8kraaisgtemnl8p51okb23oo.apps.googleusercontent.com',
    iosClientId: '33711759292-aerbhovdc49ccuao2jo7bku99562mvjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.aksara',
  );

}